# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Created on: 2015-02-24 18:53:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("c:/program files (x86)/DataEast/xtoolspro 9.0/Toolbox/XTools Pro.tbx")


# Local variables:
mw_Pump_shp = "C:\\_Model\\Output\\SHP_WGS\\mw_Pump.shp"
mw_Valve_shp = "C:\\_Model\\Output\\SHP_WGS\\mw_Valve.shp"
mw_Pump_pt_shp = "C:\\_Model\\Output\\SHP_WGS\\mw_Pump_pt.shp"
mw_Valve_pt_shp = "C:\\_Model\\Output\\SHP_WGS\\mw_Valve_pt.shp"

# Process: Convert Features to Centroids
arcpy.gp.toolbox = "c:/program files (x86)/DataEast/xtoolspro 9.0/Toolbox/XTools Pro.tbx";
# Warning: the toolbox c:/program files (x86)/DataEast/xtoolspro 9.0/Toolbox/XTools Pro.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.XToolsPro_Features2Centroids(...) with arcpy.XToolsPro_Features2Centroids_ALIAS(...)
arcpy.gp.XToolsPro_Features2Centroids(mw_Pump_shp, mw_Pump_pt_shp, "CENTER_POINT")

# Process: Convert Features to Centroids (2)
arcpy.gp.toolbox = "c:/program files (x86)/DataEast/xtoolspro 9.0/Toolbox/XTools Pro.tbx";
# Warning: the toolbox c:/program files (x86)/DataEast/xtoolspro 9.0/Toolbox/XTools Pro.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.XToolsPro_Features2Centroids(...) with arcpy.XToolsPro_Features2Centroids_ALIAS(...)
arcpy.gp.XToolsPro_Features2Centroids(mw_Valve_shp, mw_Valve_pt_shp, "CENTER_POINT")

